# creating build pipeline for dotnet application
stages:
  - stage: continousintegration
    displayName: continous-integration
    jobs:
      - job: dotnetbuild
        displayName: dotnet-job
        steps:
        - script: dotnet restore
          displayName: restore
        - script: dotnet build
          displayName: build
        - script: dotnet test
          displayName: test
        - script: dotnet publish
          displayName: publish 
        - script: dotnet publish artifact
          displayName: artifact  

       

            
    